product-name: p-healthwatch
network-properties:
  network:
    name: ((network_name))
  service_network:
    name: ((service_network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-properties:
  .healthwatch-forwarder.boshhealth_instance_count:
    value: ((healthwatch-forwarder_boshhealth_instance_count))
  .healthwatch-forwarder.boshtasks_instance_count:
    value: ((healthwatch-forwarder_boshtasks_instance_count))
  .healthwatch-forwarder.canary_instance_count:
    value: ((healthwatch-forwarder_canary_instance_count))
  .healthwatch-forwarder.cli_instance_count:
    value: ((healthwatch-forwarder_cli_instance_count))
  .healthwatch-forwarder.health_check_az:
    value: ((healthwatch-forwarder_health_check_az))
  .healthwatch-forwarder.ingestor_instance_count:
    value: ((healthwatch-forwarder_ingestor_instance_count))
  .healthwatch-forwarder.opsman_instance_count:
    value: ((healthwatch-forwarder_opsman_instance_count))
  .healthwatch-forwarder.publish_to_eva:
    value: ((healthwatch-forwarder_publish_to_eva))
  .healthwatch-forwarder.worker_instance_count:
    value: ((healthwatch-forwarder_worker_instance_count))
  .properties.boshtasks:
    value: enable
  .properties.boshtasks.enable.bosh_taskcheck_password:
    value:
      secret: ((boshtasks_enable_bosh_taskcheck_password))
  .properties.boshtasks.enable.bosh_taskcheck_username:
    value: ((boshtasks_enable_bosh_taskcheck_username))
  .properties.indicators_selector:
    value: "No"
  .properties.opsman:
    value: enable
  .properties.opsman.enable.url:
    value: ((opsman_enable_url))
  .properties.syslog_selector:
    value: "No"
resource-config:
  healthwatch-forwarder:
    instance_type:
      id: ((healthwatch-forwarder_instance_type))
    instances: ((healthwatch-forwarder_instances))
    persistent_disk:
      size_mb: ((healthwatch-forwarder_persistent_disk_size))
    max_in_flight: ((healthwatch-forwarder_max_in_flight))
  mysql:
    instance_type:
      id: ((mysql_instance_type))
    instances: ((mysql_instances))
    persistent_disk:
      size_mb: ((mysql_persistent_disk_size))
    max_in_flight: ((mysql_max_in_flight))
  redis:
    instance_type:
      id: ((redis_instance_type))
    instances: ((redis_instances))
    persistent_disk:
      size_mb: ((redis_persistent_disk_size))
    max_in_flight: ((redis_max_in_flight))
errand-config:
  cleanup:
    pre-delete-state: ((cleanup_pre_delete_state))
  push-apps:
    post-deploy-state: ((push-apps_post_deploy_state))
  smoke-tests:
    post-deploy-state: ((smoke-tests_post_deploy_state))
  validate-expected-metrics:
    post-deploy-state: ((validate-expected-metrics_post_deploy_state))
